CREATE TABLE IF NOT EXISTS deployment_runner (
  id TEXT PRIMARY KEY,
  phase TEXT NOT NULL,
  ticket TEXT NOT NULL DEFAULT '',
  branch TEXT NOT NULL DEFAULT '',
  environment TEXT NOT NULL DEFAULT 'Production',
  claim_until TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  attempts INTEGER NOT NULL DEFAULT 0,
  message TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
