// Package archive stores the exact uploaded ZIP in R2 and its version history in D1.
package archive

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path"
	"strconv"
	"strings"
	"time"

	"devcontrol/pkg/d1"
)

type Record struct {
	ID string `json:"id"`
	Scope string `json:"scope"`
	Target string `json:"target"`
	Filename string `json:"filename"`
	SizeBytes int64 `json:"size_bytes"`
	SHA256 string `json:"sha256"`
	Status string `json:"status"`
	Source string `json:"source"`
	CreatedAt string `json:"created_at"`
	ObjectKey string `json:"-"`
}

type queryFunc func(string, ...interface{}) ([]map[string]interface{}, error)

type Store struct {
	query queryFunc
	client *http.Client
	endpoint string
	account string
	bucket string
	token string
}

func New() (*Store, error) {
	account, bucket, token := os.Getenv("CF_ACCOUNT_ID"), os.Getenv("CF_R2_BUCKET"), os.Getenv("CF_API_TOKEN")
	if account == "" || bucket == "" || token == "" {
		return nil, fmt.Errorf("penyimpanan R2 belum dikonfigurasi: isi CF_R2_BUCKET dan kredensial Cloudflare dengan izin R2 Read & Write")
	}
	return &Store{query: d1.Query, client: &http.Client{Timeout: 25 * time.Second},
		endpoint: "https://api.cloudflare.com/client/v4", account: account, bucket: bucket, token: token}, nil
}

func (s *Store) objectURL(key string) string {
	// Keys are generated by the server and have a fixed, URL-safe form.
	return s.endpoint + "/accounts/" + url.PathEscape(s.account) + "/r2/buckets/" + url.PathEscape(s.bucket) + "/objects/" + key
}

// BucketStatus only inspects the configured private bucket. A 404 is the
// only reason to create it; permissions or transport errors are reported.
func (s *Store) BucketStatus() (bool, error) {
	req, err := http.NewRequest(http.MethodGet, s.endpoint+"/accounts/"+url.PathEscape(s.account)+"/r2/buckets/"+url.PathEscape(s.bucket), nil)
	if err != nil { return false, err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return false, err }
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound { return false, nil }
	var result struct {
		Success bool `json:"success"`
		Errors []struct { Message string `json:"message"` } `json:"errors"`
	}
	if err := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&result); err != nil { return false, err }
	if resp.StatusCode >= 300 || !result.Success {
		message := fmt.Sprintf("HTTP %d", resp.StatusCode)
		if len(result.Errors) > 0 { message = result.Errors[0].Message }
		return false, fmt.Errorf("memeriksa bucket R2: %s", message)
	}
	return true, nil
}

// EnsureBucket prepares one bucket per installation, then verifies both object
// write and read with a temporary probe. It never alters an existing archive.
func (s *Store) EnsureBucket() (bool, error) {
	found, err := s.BucketStatus()
	if err != nil { return false, err }
	created := false
	if !found {
		body, _ := json.Marshal(map[string]string{"name": s.bucket})
		req, err := http.NewRequest(http.MethodPost, s.endpoint+"/accounts/"+url.PathEscape(s.account)+"/r2/buckets", bytes.NewReader(body))
		if err != nil { return false, err }
		req.Header.Set("Authorization", "Bearer "+s.token)
		req.Header.Set("Content-Type", "application/json")
		resp, err := s.client.Do(req)
		if err != nil { return false, err }
		var result struct {
			Success bool `json:"success"`
			Errors []struct { Message string `json:"message"` } `json:"errors"`
		}
		decodeErr := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&result)
		resp.Body.Close()
		if decodeErr != nil { return false, fmt.Errorf("respons pembuatan R2: %w", decodeErr) }
		if resp.StatusCode >= 300 || !result.Success {
			// Another setup request may have created the same bucket meanwhile.
			exists, checkErr := s.BucketStatus()
			if checkErr != nil || !exists {
				message := fmt.Sprintf("HTTP %d", resp.StatusCode)
				if len(result.Errors) > 0 { message = result.Errors[0].Message }
				if checkErr != nil { message += ": " + checkErr.Error() }
				return false, fmt.Errorf("bucket R2 gagal dibuat: %s", message)
			}
		} else { created = true }
	}
	key := fmt.Sprintf("setup-check/%d", time.Now().UnixNano())
	data := []byte("devcontrol-r2-read-write-check")
	if err := s.put(key, data); err != nil { return created, err }
	defer s.remove(key)
	req, err := http.NewRequest(http.MethodGet, s.objectURL(key), nil)
	if err != nil { return created, err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return created, err }
	defer resp.Body.Close()
	read, err := io.ReadAll(io.LimitReader(resp.Body, int64(len(data)+1)))
	if err != nil || resp.StatusCode != http.StatusOK || !bytes.Equal(read, data) {
		return created, fmt.Errorf("verifikasi baca R2 gagal (HTTP %d): %v", resp.StatusCode, err)
	}
	return created, nil
}

func (s *Store) put(key string, data []byte) error {
	req, err := http.NewRequest(http.MethodPut, s.objectURL(key), bytes.NewReader(data))
	if err != nil { return err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	req.Header.Set("Content-Type", "application/octet-stream")
	resp, err := s.client.Do(req)
	if err != nil { return err }
	defer resp.Body.Close()
	var result struct {
		Success bool `json:"success"`
		Result struct { Key string `json:"key"`; Size string `json:"size"` } `json:"result"`
		Errors []struct { Message string `json:"message"` } `json:"errors"`
	}
	if err := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&result); err != nil {
		return fmt.Errorf("respons R2 tidak valid (HTTP %d): %w", resp.StatusCode, err)
	}
	if resp.StatusCode >= 300 || !result.Success || result.Result.Key != key ||
		(result.Result.Size != "" && result.Result.Size != strconv.Itoa(len(data))) {
		message := fmt.Sprintf("HTTP %d", resp.StatusCode)
		if len(result.Errors) > 0 { message = result.Errors[0].Message }
		return fmt.Errorf("R2 tidak mengonfirmasi penyimpanan objek: %s", message)
	}
	return nil
}

func (s *Store) remove(key string) {
	req, err := http.NewRequest(http.MethodDelete, s.objectURL(key), nil)
	if err != nil { return }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err == nil { resp.Body.Close() }
}

func cleanFilename(name string) string {
	name = path.Base(strings.ReplaceAll(name, "\\", "/"))
	name = strings.Map(func(r rune) rune {
		if r < 32 || r == 127 || r == '"' || r == '/' || r == '\\' { return '_' }
		return r
	}, name)
	if len(name) > 140 { name = name[:136] + ".zip" }
	if name == "." || name == "" { name = "source.zip" }
	return name
}

func Digest(data []byte) string { sum := sha256.Sum256(data); return hex.EncodeToString(sum[:]) }

// Save returns only after R2 confirms the bytes AND D1 indexes the object.
// A failed save never changes which version is current.
func (s *Store) Save(scope, target, filename, source, status string, data []byte) (Record, error) {
	var rec Record
	if len(data) == 0 || (status != "pending" && status != "current") { return rec, fmt.Errorf("arsip kosong atau status tidak valid") }
	idBytes := make([]byte, 16)
	if _, err := rand.Read(idBytes); err != nil { return rec, err }
	rec = Record{ID: hex.EncodeToString(idBytes), Scope: scope, Target: target,
		Filename: cleanFilename(filename), SizeBytes: int64(len(data)), SHA256: Digest(data),
		Source: source, Status: status}
	rec.ObjectKey = "archives/" + rec.ID + ".zip"
	if err := s.put(rec.ObjectKey, data); err != nil { return Record{}, err }
	_, err := s.query(`INSERT INTO zip_archives (id, scope, target, filename, object_key, size_bytes, sha256, status, source)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`, rec.ID, rec.Scope, rec.Target, rec.Filename, rec.ObjectKey,
		rec.SizeBytes, rec.SHA256, rec.Status, rec.Source)
	if err != nil {
		s.remove(rec.ObjectKey)
		return Record{}, fmt.Errorf("ZIP tersimpan di R2 tetapi gagal dicatat di D1: %w", err)
	}
	return rec, nil
}

func (s *Store) HasCurrent(scope, target string) (bool, error) {
	rows, err := s.query(`SELECT * FROM zip_archives WHERE scope = ? AND target = ? AND status = 'current' LIMIT 1`, scope, target)
	if err != nil || len(rows) == 0 { return false, err }
	if _, err := s.Download(fromRow(rows[0])); err != nil {
		return false, fmt.Errorf("ZIP versi sebelumnya tidak dapat dibaca: %w", err)
	}
	return true, nil
}

func fromRow(row map[string]interface{}) Record {
	str := func(key string) string { value, _ := row[key].(string); return value }
	var size int64
	switch value := row["size_bytes"].(type) {
	case float64: size = int64(value)
	case int64: size = value
	}
	return Record{ID: str("id"), Scope: str("scope"), Target: str("target"), Filename: str("filename"),
		SizeBytes: size, SHA256: str("sha256"), Status: str("status"), Source: str("source"),
		CreatedAt: str("created_at"), ObjectKey: str("object_key")}
}

func (s *Store) Get(id string) (Record, error) {
	rows, err := s.query(`SELECT * FROM zip_archives WHERE id = ? LIMIT 1`, id)
	if err != nil { return Record{}, err }
	if len(rows) == 0 { return Record{}, fmt.Errorf("arsip tidak ditemukan") }
	return fromRow(rows[0]), nil
}

func (s *Store) Verify(id, scope, target string, data []byte) error {
	rec, err := s.Get(id)
	if err != nil { return err }
	if rec.Scope != scope || rec.Target != target || rec.SizeBytes != int64(len(data)) || rec.SHA256 != Digest(data) || rec.Status != "pending" {
		return fmt.Errorf("arsip ZIP tidak cocok dengan sesi update atau tidak lagi menunggu proses")
	}
	return nil
}

func (s *Store) Fail(id string) error {
	_, err := s.query(`UPDATE zip_archives SET status = 'failed' WHERE id = ? AND status = 'pending'`, id)
	return err
}

// Promote changes the current pointer and archives the previous version in one D1 statement.
func (s *Store) Promote(id, scope, target string) error {
	rows, err := s.query(`WITH candidate AS MATERIALIZED
		(SELECT id FROM zip_archives WHERE id = ? AND scope = ? AND target = ? AND status = 'pending'),
		affected AS MATERIALIZED
		(SELECT id FROM zip_archives WHERE scope = ? AND target = ? AND status = 'current'
		 UNION SELECT id FROM candidate)
		UPDATE zip_archives SET status = CASE WHEN id = ? THEN 'current' ELSE 'previous' END
		WHERE id IN (SELECT id FROM affected) AND EXISTS (SELECT 1 FROM candidate)
		RETURNING id, status`, id, scope, target, scope, target, id)
	if err != nil { return err }
	for _, row := range rows {
		if row["id"] == id && row["status"] == "current" { return nil }
	}
	return fmt.Errorf("versi baru tidak dapat ditandai berhasil; periksa arsip")
}

func (s *Store) List(offset int) ([]Record, bool, error) {
	if offset < 0 { offset = 0 }
	rows, err := s.query(`SELECT * FROM zip_archives ORDER BY created_at DESC, rowid DESC LIMIT 51 OFFSET ?`, offset)
	if err != nil { return nil, false, err }
	more := len(rows) > 50
	if more { rows = rows[:50] }
	list := make([]Record, 0, len(rows))
	for _, row := range rows { list = append(list, fromRow(row)) }
	return list, more, nil
}

// DeleteTarget removes only the ZIP objects belonging to one application or
// self-update target. Each D1 row is removed after its R2 object is gone, so
// a failed request can safely resume on the next attempt.
func (s *Store) DeleteTarget(scope, target string) error {
	rows, err := s.query(`SELECT id, object_key FROM zip_archives WHERE scope = ? AND target = ?`, scope, target)
	if err != nil { return err }
	for _, row := range rows {
		id, _ := row["id"].(string)
		key, _ := row["object_key"].(string)
		if len(id) != 32 || strings.Trim(id, "0123456789abcdef") != "" || key != "archives/"+id+".zip" {
			return fmt.Errorf("kunci arsip tidak valid untuk %s", target)
		}
		req, err := http.NewRequest(http.MethodDelete, s.objectURL(key), nil)
		if err != nil { return err }
		req.Header.Set("Authorization", "Bearer "+s.token)
		resp, err := s.client.Do(req)
		if err != nil { return err }
		if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusNoContent && resp.StatusCode != http.StatusNotFound {
			resp.Body.Close()
			return fmt.Errorf("gagal menghapus ZIP %s di R2 (HTTP %d)", id, resp.StatusCode)
		}
		if resp.StatusCode == http.StatusOK {
			var result struct { Success bool `json:"success"` }
			decodeErr := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&result)
			resp.Body.Close()
			if decodeErr != nil || !result.Success { return fmt.Errorf("R2 tidak mengonfirmasi penghapusan ZIP %s: %v", id, decodeErr) }
		} else { resp.Body.Close() }
		if _, err := s.query(`DELETE FROM zip_archives WHERE id = ? AND scope = ? AND target = ?`, id, scope, target); err != nil { return err }
	}
	return nil
}

func (s *Store) Download(rec Record) ([]byte, error) {
	if !strings.HasPrefix(rec.ObjectKey, "archives/") || !strings.HasSuffix(rec.ObjectKey, ".zip") { return nil, fmt.Errorf("kunci objek tidak valid") }
	req, err := http.NewRequest(http.MethodGet, s.objectURL(rec.ObjectKey), nil)
	if err != nil { return nil, err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return nil, err }
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK { return nil, fmt.Errorf("R2 mengembalikan HTTP %d", resp.StatusCode) }
	data, err := io.ReadAll(io.LimitReader(resp.Body, (4<<20)+1))
	if err != nil { return nil, err }
	if int64(len(data)) != rec.SizeBytes || Digest(data) != rec.SHA256 { return nil, fmt.Errorf("ZIP arsip tidak lengkap atau berubah") }
	return data, nil
}

// Thumbnails share the private bucket with ZIP archives. Legacy images use a
// deterministic key; direct uploads use an immutable key under that prefix.
func validThumbnailKey(key string) bool {
	if !strings.HasPrefix(key, "thumbnails/") || !strings.HasSuffix(key, ".img") { return false }
	part := strings.TrimSuffix(strings.TrimPrefix(key, "thumbnails/"), ".img")
	parts := strings.Split(part, "/")
	if len(parts) == 1 { return len(parts[0]) == 64 && strings.Trim(parts[0], "0123456789abcdef") == "" }
	return len(parts) == 2 && len(parts[0]) == 64 && len(parts[1]) == 32 &&
		strings.Trim(parts[0], "0123456789abcdef") == "" && strings.Trim(parts[1], "0123456789abcdef") == ""
}

func (s *Store) SaveThumbnail(key string, data []byte) error {
	if !validThumbnailKey(key) || len(data) == 0 || len(data) > 1<<20 { return fmt.Errorf("gambar thumbnail tidak valid") }
	return s.put(key, data)
}

func (s *Store) ReadThumbnail(key string) ([]byte, error) {
	if !validThumbnailKey(key) { return nil, fmt.Errorf("kunci thumbnail tidak valid") }
	req, err := http.NewRequest(http.MethodGet, s.objectURL(key), nil)
	if err != nil { return nil, err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return nil, err }
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK { return nil, fmt.Errorf("R2 mengembalikan HTTP %d", resp.StatusCode) }
	data, err := io.ReadAll(io.LimitReader(resp.Body, (1<<20)+1))
	if err != nil { return nil, err }
	if len(data) == 0 || len(data) > 1<<20 { return nil, fmt.Errorf("gambar thumbnail terlalu besar atau kosong") }
	return data, nil
}

func (s *Store) DeleteThumbnail(key string) error {
	if !validThumbnailKey(key) { return fmt.Errorf("kunci thumbnail tidak valid") }
	req, err := http.NewRequest(http.MethodDelete, s.objectURL(key), nil)
	if err != nil { return err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return err }
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound || resp.StatusCode == http.StatusNoContent { return nil }
	if resp.StatusCode != http.StatusOK { return fmt.Errorf("gagal menghapus thumbnail di R2 (HTTP %d)", resp.StatusCode) }
	var result struct {
		Success bool `json:"success"`
		Errors []struct { Message string `json:"message"` } `json:"errors"`
	}
	if err := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&result); err != nil { return err }
	if !result.Success {
		if len(result.Errors) > 0 && result.Errors[0].Message != "" {
			return fmt.Errorf("R2 menolak penghapusan thumbnail: %s", result.Errors[0].Message)
		}
		return fmt.Errorf("R2 tidak mengonfirmasi penghapusan thumbnail")
	}
	return nil
}

// Branding icons are small, public PNG variants stored in the same private
// bucket. Only the server-generated version and these three names are valid.
func validBrandingKey(key string) bool {
	parts := strings.Split(key, "/")
	return len(parts) == 3 && parts[0] == "branding" && len(parts[1]) == 32 &&
		strings.Trim(parts[1], "0123456789abcdef") == "" &&
		(parts[2] == "192.png" || parts[2] == "512.png" || parts[2] == "maskable.png")
}

func (s *Store) SaveBranding(key string, data []byte) error {
	if !validBrandingKey(key) || len(data) == 0 || len(data) > 2<<20 { return fmt.Errorf("ikon aplikasi tidak valid") }
	return s.put(key, data)
}

func (s *Store) ReadBranding(key string) ([]byte, error) {
	if !validBrandingKey(key) { return nil, fmt.Errorf("kunci ikon aplikasi tidak valid") }
	req, err := http.NewRequest(http.MethodGet, s.objectURL(key), nil)
	if err != nil { return nil, err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return nil, err }
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK { return nil, fmt.Errorf("R2 mengembalikan HTTP %d", resp.StatusCode) }
	data, err := io.ReadAll(io.LimitReader(resp.Body, (2<<20)+1))
	if err != nil { return nil, err }
	if len(data) == 0 || len(data) > 2<<20 { return nil, fmt.Errorf("ikon aplikasi terlalu besar atau kosong") }
	return data, nil
}

func (s *Store) DeleteBranding(key string) error {
	if !validBrandingKey(key) { return fmt.Errorf("kunci ikon aplikasi tidak valid") }
	req, err := http.NewRequest(http.MethodDelete, s.objectURL(key), nil)
	if err != nil { return err }
	req.Header.Set("Authorization", "Bearer "+s.token)
	resp, err := s.client.Do(req)
	if err != nil { return err }
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound || resp.StatusCode == http.StatusNoContent { return nil }
	if resp.StatusCode != http.StatusOK { return fmt.Errorf("R2 gagal menghapus ikon (HTTP %d)", resp.StatusCode) }
	var result struct { Success bool `json:"success"` }
	if err := json.NewDecoder(io.LimitReader(resp.Body, 64<<10)).Decode(&result); err != nil { return err }
	if !result.Success { return fmt.Errorf("R2 tidak mengonfirmasi penghapusan ikon") }
	return nil
}
