#!/usr/bin/env node
// Keep the SQL deployed by the Vercel Go function identical to db/schema.sql.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const clean = (sql) => sql.split("\n").filter((line) => !line.trimStart().startsWith("--"))
  .join("\n").split(";").map((statement) => statement.trim()).filter(Boolean);
const schema = readFileSync("db/schema.sql", "utf8");
const statements = clean(schema);
const tables = {};
const types = {};
for (const match of schema.matchAll(/CREATE TABLE IF NOT EXISTS\s+([a-z_]+)\s*\(([\s\S]*?)\n\);/g)) {
  const columns = [...match[2].matchAll(/^\s+([a-z_][a-z0-9_]*)\s+(INTEGER|REAL|TEXT)\b/gm)];
  tables[match[1]] = columns.map((column) => column[1]);
  types[match[1]] = Object.fromEntries(columns.map((column) => [column[1], column[2]]));
}
const indexes = [...schema.matchAll(/CREATE (?:UNIQUE )?INDEX IF NOT EXISTS\s+([a-z_]+)/g)].map((match) => match[1]);
const migrations = readdirSync("db/migrations").filter((name) => /^\d+_.*\.sql$/.test(name)).sort()
  .flatMap((name) => clean(readFileSync(`db/migrations/${name}`, "utf8"))
    .map((sql) => ({ version: name.slice(0, 3), sql })));
const q = JSON.stringify;
const output = [
  "// Code generated by node scripts/generate-schema.mjs; DO NOT EDIT.",
  "package setup", "",
  "type migrationStatement struct { Version string; SQL string }", "",
  "var schemaStatements = []string{", ...statements.map((sql) => `  ${q(sql)},`), "}", "",
  "var migrationStatements = []migrationStatement{",
  ...migrations.map(({ version, sql }) => `  {${q(version)}, ${q(sql)}},`), "}", "",
  "var expectedColumns = map[string][]string{",
  ...Object.entries(tables).map(([name, columns]) =>
    `  ${q(name)}: {${columns.map(q).join(", ")}},`), "}", "",
  "var expectedTypes = map[string]map[string]string{",
  ...Object.entries(types).map(([name, columns]) =>
    `  ${q(name)}: {${Object.entries(columns).map(([column, type]) => `${q(column)}: ${q(type)}`).join(", ")}},`), "}", "",
  `var expectedIndexes = []string{${indexes.map(q).join(", ")}}`, "",
].join("\n");
writeFileSync("pkg/setup/schema_generated.go", output);
console.log(`Generated ${statements.length} D1 statements from db/schema.sql and ${migrations.length} legacy migration statements.`);
