// Code generated by node scripts/generate-schema.mjs; DO NOT EDIT.
package setup

type migrationStatement struct { Version string; SQL string }

var schemaStatements = []string{
  "CREATE TABLE IF NOT EXISTS overview_stats (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  active_projects INTEGER NOT NULL,\n  active_projects_change REAL NOT NULL,\n  deployments_today INTEGER NOT NULL,\n  deployments_change REAL NOT NULL,\n  uptime REAL NOT NULL,\n  uptime_change REAL NOT NULL,\n  open_incidents INTEGER NOT NULL,\n  incidents_change REAL NOT NULL,\n  updated_at TEXT DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS environments (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  region TEXT NOT NULL,\n  version TEXT NOT NULL,\n  status TEXT NOT NULL CHECK (status IN ('Healthy', 'Online', 'Degraded', 'Down'))\n)",
  "CREATE TABLE IF NOT EXISTS deployment_pipeline (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  stage TEXT NOT NULL,\n  duration TEXT NOT NULL,\n  status TEXT NOT NULL CHECK (status IN ('Success', 'Running', 'Pending', 'Failed')),\n  position INTEGER NOT NULL\n)",
  "CREATE TABLE IF NOT EXISTS deployment_jobs (\n  id TEXT PRIMARY KEY,\n  kind TEXT NOT NULL CHECK (kind IN ('new_app', 'update_app', 'self_update')),\n  target TEXT NOT NULL,\n  lock_key TEXT NOT NULL,\n  status TEXT NOT NULL CHECK (status IN ('Running', 'Success', 'Failed', 'Interrupted')),\n  stages TEXT NOT NULL,\n  lease_until TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_deployment_jobs_running_target ON deployment_jobs (lock_key) WHERE status = 'Running'",
  "CREATE INDEX IF NOT EXISTS idx_deployment_jobs_updated ON deployment_jobs (updated_at DESC)",
  "CREATE TABLE IF NOT EXISTS services (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  name TEXT NOT NULL,\n  status TEXT NOT NULL CHECK (status IN ('Healthy', 'Degraded', 'Down')),\n  uptime REAL NOT NULL,\n  version TEXT NOT NULL,\n  repo TEXT,\n  branch TEXT DEFAULT 'main',\n  app_url TEXT\n)",
  "CREATE TABLE IF NOT EXISTS activity_log (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  title TEXT NOT NULL,\n  description TEXT NOT NULL,\n  icon TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS live_logs (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  level TEXT NOT NULL CHECK (level IN ('INFO', 'WARN', 'ERROR')),\n  message TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS api_performance (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  response_time_ms INTEGER NOT NULL,\n  response_time_change REAL NOT NULL,\n  request_volume INTEGER NOT NULL,\n  request_volume_change REAL NOT NULL,\n  error_rate REAL NOT NULL,\n  error_rate_change REAL NOT NULL,\n  updated_at TEXT DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS infra_metrics (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  metric TEXT NOT NULL CHECK (metric IN ('cpu', 'memory', 'network', 'requests')),\n  value REAL NOT NULL,\n  recorded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_infra_metrics_metric_time ON infra_metrics (metric, recorded_at)",
  "CREATE INDEX IF NOT EXISTS idx_live_logs_created_at ON live_logs (created_at)",
  "CREATE INDEX IF NOT EXISTS idx_activity_created_at ON activity_log (created_at)",
  "CREATE TABLE IF NOT EXISTS zip_archives (\n  id TEXT PRIMARY KEY,\n  scope TEXT NOT NULL CHECK (scope IN ('app', 'self')),\n  target TEXT NOT NULL,\n  filename TEXT NOT NULL,\n  object_key TEXT NOT NULL,\n  size_bytes INTEGER NOT NULL,\n  sha256 TEXT NOT NULL,\n  status TEXT NOT NULL CHECK (status IN ('pending', 'current', 'previous', 'failed')),\n  source TEXT NOT NULL CHECK (source IN ('upload', 'github_snapshot')),\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_zip_archives_target ON zip_archives (scope, target, created_at DESC)",
  "CREATE TABLE IF NOT EXISTS project_thumbnails (\n  repo TEXT PRIMARY KEY COLLATE NOCASE,\n  version TEXT NOT NULL,\n  object_key TEXT,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS project_thumbnail_uploads (\n  id TEXT PRIMARY KEY,\n  repo TEXT NOT NULL COLLATE NOCASE,\n  object_key TEXT NOT NULL,\n  content_type TEXT NOT NULL,\n  size_bytes INTEGER NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_project_thumbnail_uploads_repo ON project_thumbnail_uploads (repo)",
  "CREATE INDEX IF NOT EXISTS idx_project_thumbnail_uploads_time ON project_thumbnail_uploads (created_at)",
  "CREATE TABLE IF NOT EXISTS project_thumbnail_objects (\n  object_key TEXT PRIMARY KEY,\n  repo TEXT NOT NULL COLLATE NOCASE,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_project_thumbnail_objects_repo ON project_thumbnail_objects (repo)",
  "CREATE TABLE IF NOT EXISTS app_branding (\n  id INTEGER PRIMARY KEY CHECK (id = 1),\n  version TEXT NOT NULL,\n  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS schema_migrations (\n  version TEXT PRIMARY KEY,\n  applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE TABLE IF NOT EXISTS managed_apis (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  project TEXT NOT NULL,\n  path TEXT NOT NULL,\n  method TEXT NOT NULL CHECK (method IN ('GET', 'HEAD')),\n  environment TEXT NOT NULL,\n  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_managed_apis_project ON managed_apis (project)",
  "CREATE TABLE IF NOT EXISTS api_keys (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  key_prefix TEXT NOT NULL,\n  key_hash TEXT NOT NULL UNIQUE,\n  scopes TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,\n  revoked_at TEXT\n)",
  "CREATE INDEX IF NOT EXISTS idx_api_keys_active ON api_keys (key_hash, revoked_at)",
  "CREATE TABLE IF NOT EXISTS api_check_metrics (\n  id TEXT PRIMARY KEY,\n  api_id TEXT NOT NULL,\n  status_code INTEGER NOT NULL,\n  latency_ms INTEGER NOT NULL,\n  checked_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_api_check_metrics_time ON api_check_metrics (checked_at DESC)",
  "CREATE TABLE IF NOT EXISTS admin_audit_log (\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\n  action TEXT NOT NULL,\n  target TEXT NOT NULL,\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)",
  "CREATE INDEX IF NOT EXISTS idx_admin_audit_time ON admin_audit_log (created_at DESC)",
}

var migrationStatements = []migrationStatement{
  {"001", "ALTER TABLE services ADD COLUMN app_url TEXT"},
  {"002", "ALTER TABLE services ADD COLUMN repo TEXT"},
  {"002", "ALTER TABLE services ADD COLUMN branch TEXT DEFAULT 'main'"},
  {"003", "CREATE TABLE IF NOT EXISTS zip_archives (\n  id TEXT PRIMARY KEY,\n  scope TEXT NOT NULL CHECK (scope IN ('app', 'self')),\n  target TEXT NOT NULL,\n  filename TEXT NOT NULL,\n  object_key TEXT NOT NULL,\n  size_bytes INTEGER NOT NULL,\n  sha256 TEXT NOT NULL,\n  status TEXT NOT NULL CHECK (status IN ('pending', 'current', 'previous', 'failed')),\n  source TEXT NOT NULL CHECK (source IN ('upload', 'github_snapshot')),\n  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP\n)"},
  {"003", "CREATE INDEX IF NOT EXISTS idx_zip_archives_target ON zip_archives (scope, target, created_at DESC)"},
  {"004", "ALTER TABLE project_thumbnails ADD COLUMN object_key TEXT"},
}

var expectedColumns = map[string][]string{
  "overview_stats": {"id", "active_projects", "active_projects_change", "deployments_today", "deployments_change", "uptime", "uptime_change", "open_incidents", "incidents_change", "updated_at"},
  "environments": {"id", "name", "region", "version", "status"},
  "deployment_pipeline": {"id", "stage", "duration", "status", "position"},
  "deployment_jobs": {"id", "kind", "target", "lock_key", "status", "stages", "lease_until", "created_at", "updated_at"},
  "services": {"id", "name", "status", "uptime", "version", "repo", "branch", "app_url"},
  "activity_log": {"id", "title", "description", "icon", "created_at"},
  "live_logs": {"id", "level", "message", "created_at"},
  "api_performance": {"id", "response_time_ms", "response_time_change", "request_volume", "request_volume_change", "error_rate", "error_rate_change", "updated_at"},
  "infra_metrics": {"id", "metric", "value", "recorded_at"},
  "zip_archives": {"id", "scope", "target", "filename", "object_key", "size_bytes", "sha256", "status", "source", "created_at"},
  "project_thumbnails": {"repo", "version", "object_key", "updated_at"},
  "project_thumbnail_uploads": {"id", "repo", "object_key", "content_type", "size_bytes", "created_at"},
  "project_thumbnail_objects": {"object_key", "repo", "created_at"},
  "app_branding": {"id", "version", "updated_at"},
  "schema_migrations": {"version", "applied_at"},
  "managed_apis": {"id", "name", "project", "path", "method", "environment", "enabled", "created_at"},
  "api_keys": {"id", "name", "key_prefix", "key_hash", "scopes", "created_at", "revoked_at"},
  "api_check_metrics": {"id", "api_id", "status_code", "latency_ms", "checked_at"},
  "admin_audit_log": {"id", "action", "target", "created_at"},
}

var expectedTypes = map[string]map[string]string{
  "overview_stats": {"id": "INTEGER", "active_projects": "INTEGER", "active_projects_change": "REAL", "deployments_today": "INTEGER", "deployments_change": "REAL", "uptime": "REAL", "uptime_change": "REAL", "open_incidents": "INTEGER", "incidents_change": "REAL", "updated_at": "TEXT"},
  "environments": {"id": "INTEGER", "name": "TEXT", "region": "TEXT", "version": "TEXT", "status": "TEXT"},
  "deployment_pipeline": {"id": "INTEGER", "stage": "TEXT", "duration": "TEXT", "status": "TEXT", "position": "INTEGER"},
  "deployment_jobs": {"id": "TEXT", "kind": "TEXT", "target": "TEXT", "lock_key": "TEXT", "status": "TEXT", "stages": "TEXT", "lease_until": "TEXT", "created_at": "TEXT", "updated_at": "TEXT"},
  "services": {"id": "INTEGER", "name": "TEXT", "status": "TEXT", "uptime": "REAL", "version": "TEXT", "repo": "TEXT", "branch": "TEXT", "app_url": "TEXT"},
  "activity_log": {"id": "INTEGER", "title": "TEXT", "description": "TEXT", "icon": "TEXT", "created_at": "TEXT"},
  "live_logs": {"id": "INTEGER", "level": "TEXT", "message": "TEXT", "created_at": "TEXT"},
  "api_performance": {"id": "INTEGER", "response_time_ms": "INTEGER", "response_time_change": "REAL", "request_volume": "INTEGER", "request_volume_change": "REAL", "error_rate": "REAL", "error_rate_change": "REAL", "updated_at": "TEXT"},
  "infra_metrics": {"id": "INTEGER", "metric": "TEXT", "value": "REAL", "recorded_at": "TEXT"},
  "zip_archives": {"id": "TEXT", "scope": "TEXT", "target": "TEXT", "filename": "TEXT", "object_key": "TEXT", "size_bytes": "INTEGER", "sha256": "TEXT", "status": "TEXT", "source": "TEXT", "created_at": "TEXT"},
  "project_thumbnails": {"repo": "TEXT", "version": "TEXT", "object_key": "TEXT", "updated_at": "TEXT"},
  "project_thumbnail_uploads": {"id": "TEXT", "repo": "TEXT", "object_key": "TEXT", "content_type": "TEXT", "size_bytes": "INTEGER", "created_at": "TEXT"},
  "project_thumbnail_objects": {"object_key": "TEXT", "repo": "TEXT", "created_at": "TEXT"},
  "app_branding": {"id": "INTEGER", "version": "TEXT", "updated_at": "TEXT"},
  "schema_migrations": {"version": "TEXT", "applied_at": "TEXT"},
  "managed_apis": {"id": "TEXT", "name": "TEXT", "project": "TEXT", "path": "TEXT", "method": "TEXT", "environment": "TEXT", "enabled": "INTEGER", "created_at": "TEXT"},
  "api_keys": {"id": "TEXT", "name": "TEXT", "key_prefix": "TEXT", "key_hash": "TEXT", "scopes": "TEXT", "created_at": "TEXT", "revoked_at": "TEXT"},
  "api_check_metrics": {"id": "TEXT", "api_id": "TEXT", "status_code": "INTEGER", "latency_ms": "INTEGER", "checked_at": "TEXT"},
  "admin_audit_log": {"id": "INTEGER", "action": "TEXT", "target": "TEXT", "created_at": "TEXT"},
}

var expectedIndexes = []string{"idx_deployment_jobs_running_target", "idx_deployment_jobs_updated", "idx_infra_metrics_metric_time", "idx_live_logs_created_at", "idx_activity_created_at", "idx_zip_archives_target", "idx_project_thumbnail_uploads_repo", "idx_project_thumbnail_uploads_time", "idx_project_thumbnail_objects_repo", "idx_managed_apis_project", "idx_api_keys_active", "idx_api_check_metrics_time", "idx_admin_audit_time"}
