package reposync

import "testing"

func TestPlanSync(t *testing.T) {
	zip := []string{"package.json", "app/page.tsx", "lib/a.ts"}
	repo := []string{
		"package.json", "app/page.tsx", "lib/a.ts",
		"lib/old.ts",                      // removed from ZIP → delete
		"package-lock.json",               // generated by npm install, ZIP has none → keep
		".github/workflows/ci.yml",        // CI metadata → keep
		".gitignore", "LICENSE",           // repo metadata → keep
		"node_modules/react/index.js",     // install output committed by mistake → delete
		".next/cache/x",                   // build output → delete
		".env.local",                      // secret already in repo → keep + warn
	}
	plan := PlanSync(zip, repo)
	if len(plan.Delete) != 1 || plan.Delete[0] != "lib/old.ts" { t.Fatalf("delete = %v", plan.Delete) }
	if len(plan.Generated) != 2 { t.Fatalf("generated = %v", plan.Generated) }
	if len(plan.Kept) != 4 { t.Fatalf("kept = %v", plan.Kept) }
	if len(plan.SecretsInRepo) != 1 { t.Fatalf("secrets = %v", plan.SecretsInRepo) }
	if plan.Blocked { t.Fatal("guard tripped unexpectedly") }
}

func TestLockfileReplacedByOtherManager(t *testing.T) {
	plan := PlanSync([]string{"package.json", "pnpm-lock.yaml"}, []string{"package.json", "package-lock.json"})
	if len(plan.Delete) != 1 || plan.Delete[0] != "package-lock.json" { t.Fatalf("delete = %v", plan.Delete) }
}

func TestMassDeletionGuard(t *testing.T) {
	repo := []string{"package.json"}
	for i := 0; i < 30; i++ { repo = append(repo, "src/file"+string(rune('a'+i%26))+string(rune('a'+i/26))+".ts") }
	plan := PlanSync([]string{"package.json"}, repo)
	if !plan.Blocked || len(plan.Removed()) != 0 { t.Fatalf("guard should block: %+v", plan) }
}

func TestFilters(t *testing.T) {
	for _, path := range []string{"__MACOSX/a", "x/.DS_Store", "._file"} { if !IsJunk(path) { t.Fatal(path) } }
	for _, path := range []string{"node_modules/a/b.js", "apps/web/.next/x", "tsconfig.tsbuildinfo"} { if !IsGenerated(path) { t.Fatal(path) } }
	for _, path := range []string{"dist/index.js", "build/app.js", "src/node_modules.ts"} { if IsGenerated(path) { t.Fatal(path) } }
	if !IsSecretEnv(".env") || !IsSecretEnv("apps/web/.env.production") || IsSecretEnv(".env.example") { t.Fatal("env rules") }
}
